name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install CloudFoundry CLI
        shell: bash
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '16.14.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install

      - name: Deploy to GOV.UK PaaS
        id: deploy-to-paas
        shell: bash
        env:
          CF_DOCKER_PASSWORD: ${{ secrets.DOCKER_DEV_PASSWORD }}
          PAAS_ORGANISATION: dfe
          # This is a shared PAAS space
          PAAS_SPACE: early-careers-framework-prod
          ENV_STUB: production
          APP_NAME: cpd-information
          REMOTE_DOCKER_IMAGE_NAME: dfedigital/early-careers-framework-production
          CF_USERNAME: ${{ secrets.GOVPAAS_PROD_USERNAME }}
          CF_PASSWORD: ${{ secrets.GOVPAAS_PROD_PASSWORD }}
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth
          cf target -o "${{ env.PAAS_ORGANISATION }}" -s "${{ env.PAAS_SPACE }}"
          cf push "${{ env.APP_NAME }}"-"${{ env.ENV_STUB }}" \
            --manifest ./config/manifests/"${{ env.ENV_STUB }}"-manifest.yml \
            --strategy rolling
