name: Deploy to Review App

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  deploy:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install CloudFoundry CLI
        shell: bash
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '16.14.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Deploy to GOV.UK PaaS
        id: deploy-to-paas
        shell: bash
        env:
          PAAS_ORGANISATION: dfe
          # This is a shared PAAS space
          PAAS_SPACE: earlycareers-framework-dev
          ENV_STUB: review-app-${{ github.event.number }}
          APP_NAME: cpd-information
          CF_USERNAME: ${{ secrets.GOVPAAS_DEV_USERNAME }}
          CF_PASSWORD: ${{ secrets.GOVPAAS_DEV_PASSWORD }}
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth
          cf target -o "${{ env.PAAS_ORGANISATION }}" -s "${{ env.PAAS_SPACE }}"
          cf push "${{ env.APP_NAME }}"-"${{ env.ENV_STUB }}" \
            --var APP_NAME="${{ env.APP_NAME }}" \
            --var ENV_STUB="${{ env.ENV_STUB }}" \
            --manifest ./config/manifests/review-app-manifest.yml \
            --strategy rolling

      - name: Add PR comment with Review App link
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Created review app at https://cpd-information-review-app-${{ github.event.number }}.london.cloudapps.digital"
          check_for_duplicate_msg: true
          duplicate_msg_pattern: Created review app at*
